from typing import Any, Iterable, Iterator

import numpy as np
from numpy.typing import NDArray

SectorKey = int | tuple[int, ...]


class SectorSpec:
    @property
    def static_key(self) -> tuple[Any, ...]: ...
    def __matmul__(self, other: "SectorSpec") -> "SectorSpec": ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def quantum_dim(self, sector: SectorKey) -> int: ...


class ElementarySpace:
    @property
    def sector_spec(self) -> SectorSpec: ...
    @property
    def sectors(self) -> tuple[tuple[tuple[int, ...], int], ...]: ...
    @property
    def is_dual(self) -> bool: ...
    @property
    def static_key(self) -> tuple[Any, ...]: ...
    def dual(self) -> "ElementarySpace": ...
    def flip(self) -> "ElementarySpace": ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class ProductSpace:
    @property
    def sector_spec(self) -> SectorSpec: ...
    @property
    def spaces(self) -> tuple[ElementarySpace, ...]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ElementarySpace: ...
    def __iter__(self) -> Iterator[ElementarySpace]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class HomSpace:
    @property
    def codomain(self) -> ProductSpace: ...
    @property
    def domain(self) -> ProductSpace: ...
    @property
    def numout(self) -> int: ...
    @property
    def numin(self) -> int: ...
    @property
    def numind(self) -> int: ...
    @property
    def visible_legs(self) -> tuple[ElementarySpace, ...]: ...
    @property
    def static_key(self) -> tuple[Any, ...]: ...
    def permute(
        self,
        p_codomain: tuple[int, ...],
        p_domain: tuple[int, ...],
    ) -> "HomSpace": ...
    def flip(self, indices: tuple[int, ...]) -> "HomSpace": ...
    def insert_left_unit(self, position: int, dual: bool) -> "HomSpace": ...
    def insert_right_unit(self, position: int, dual: bool) -> "HomSpace": ...
    def remove_unit(self, index: int) -> "HomSpace": ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ElementarySpace: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class FusionTree:
    @property
    def uncoupled(self) -> tuple[tuple[int, ...], ...]: ...
    @property
    def coupled(self) -> tuple[int, ...]: ...
    @property
    def is_dual(self) -> tuple[bool, ...]: ...
    @property
    def innerlines(self) -> tuple[tuple[int, ...], ...]: ...
    @property
    def vertices(self) -> tuple[int, ...]: ...
    @property
    def static_key(self) -> tuple[Any, ...]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class SectorStructure:
    @property
    def blocksectors(self) -> tuple[tuple[int, ...], ...]: ...
    @property
    def fusiontree_pairs(self) -> tuple[tuple[FusionTree, FusionTree], ...]: ...
    @property
    def fusiontree_pair_count(self) -> int: ...
    @property
    def static_key(self) -> tuple[Any, ...]: ...
    def blocksector_index(self, sector: object) -> int | None: ...
    def fusiontree_pair_at(self, index: int) -> tuple[FusionTree, FusionTree] | None: ...
    def fusiontree_pair_index(
        self,
        row: FusionTree,
        col: FusionTree,
    ) -> int | None: ...


class BlockStructure:
    @property
    def row_dim(self) -> int: ...
    @property
    def col_dim(self) -> int: ...
    @property
    def start(self) -> int: ...
    @property
    def stop(self) -> int: ...
    @property
    def static_key(self) -> tuple[Any, ...]: ...


class SubblockStructure:
    @property
    def sizes(self) -> tuple[int, ...]: ...
    @property
    def strides(self) -> tuple[int, ...]: ...
    @property
    def offset(self) -> int: ...
    @property
    def static_key(self) -> tuple[Any, ...]: ...


class DegeneracyStructure:
    @property
    def total_dim(self) -> int: ...
    @property
    def blockstructure(self) -> tuple[BlockStructure, ...]: ...
    @property
    def subblockstructure(self) -> tuple[SubblockStructure, ...]: ...
    @property
    def static_key(self) -> tuple[Any, ...]: ...
    def subblock_at(self, index: int) -> SubblockStructure | None: ...


class AbelianTransformData:
    @property
    def coeff(self) -> float: ...
    @property
    def src(self) -> int: ...
    @property
    def dst(self) -> int: ...


class GenericTransformData:
    @property
    def src_indices(self) -> tuple[int, ...]: ...
    @property
    def dst_indices(self) -> tuple[int, ...]: ...
    @property
    def transform(self) -> NDArray[np.float64]: ...


class TreeTransformer:
    @property
    def kind(self) -> str: ...
    @property
    def has_only_unit_coefficients(self) -> bool: ...
    @property
    def abelian_data(self) -> tuple[AbelianTransformData, ...]: ...
    @property
    def generic_data(self) -> tuple[GenericTransformData, ...]: ...

U1Irrep: SectorSpec
SU2Irrep: SectorSpec
FermionParity: SectorSpec
Z2Irrep: SectorSpec
Z3Irrep: SectorSpec
Z4Irrep: SectorSpec
FermionNumber: SectorSpec
FermionParityU1Irrep: SectorSpec
U1SU2Irrep: SectorSpec
FermionParitySU2Irrep: SectorSpec
FermionParityU1SU2Irrep: SectorSpec


def native_version() -> str: ...
def make_space(
    sector_type: SectorSpec,
    sectors: tuple[tuple[tuple[int, ...], int], ...],
    is_dual: bool = False,
) -> ElementarySpace: ...
def make_product_space(
    sector_type: SectorSpec,
    spaces: Iterable[ElementarySpace],
) -> ProductSpace: ...
def make_hom_products(
    codomain: ProductSpace,
    domain: ProductSpace,
) -> HomSpace: ...
def fuse(product: ProductSpace) -> ElementarySpace: ...
def infimum_space(left: ElementarySpace, right: ElementarySpace) -> ElementarySpace: ...
def build_sectorstructure(space: HomSpace) -> SectorStructure: ...
def unique_fusiontree_pair_index(
    space: HomSpace,
    sectorstructure: SectorStructure,
    visible_sectors: tuple[SectorKey, ...],
) -> int | None: ...
def build_degeneracystructure(space: HomSpace) -> DegeneracyStructure: ...
def _build_degeneracystructure_from_sectorstructure(
    space: HomSpace,
    sectorstructure: SectorStructure,
) -> DegeneracyStructure: ...
def fusiontree_tensor(tree: FusionTree) -> NDArray[np.float64]: ...
def fusiontree_pair_tensor(row_tree: FusionTree, col_tree: FusionTree) -> NDArray[np.float64]: ...
def product_axes(
    product_space: ProductSpace,
    sectors: Iterable[SectorKey],
) -> tuple[tuple[int, int, int, int], ...]: ...
def product_dims(product_space: ProductSpace) -> tuple[int, ...]: ...
def twist_is_trivial(
    space: HomSpace,
    indices: tuple[int, ...],
) -> bool: ...
def twist_subblock_factors(
    space: HomSpace,
    sectorstructure: SectorStructure,
    indices: tuple[int, ...],
    inv: bool = False,
) -> tuple[float, ...] | None: ...
def trace_transformer(
    canonical_src: HomSpace,
    dst: HomSpace,
    canonical_sectorstructure: SectorStructure,
    dst_sectorstructure: SectorStructure,
    basis_transformer: TreeTransformer,
) -> TreeTransformer: ...
def tree_braider(
    src_space: HomSpace,
    dst_space: HomSpace,
    src_sectorstructure: SectorStructure,
    dst_sectorstructure: SectorStructure,
    p_codomain: tuple[int, ...],
    p_domain: tuple[int, ...],
    levels_codomain: tuple[int, ...],
    levels_domain: tuple[int, ...],
) -> TreeTransformer: ...
def tree_transposer(
    src_space: HomSpace,
    dst_space: HomSpace,
    src_sectorstructure: SectorStructure,
    dst_sectorstructure: SectorStructure,
    p_codomain: tuple[int, ...],
    p_domain: tuple[int, ...],
) -> TreeTransformer: ...
def flip_entries(
    src_space: HomSpace,
    dst_space: HomSpace,
    src_sectorstructure: SectorStructure,
    dst_sectorstructure: SectorStructure,
    indices: tuple[int, ...],
    inv: bool = False,
) -> tuple[tuple[int, float], ...]: ...
