#include "reduction_impl.h"

TENSOR0_STRIDE_DEFINE_REDUCTION(F32, F32)
TENSOR0_STRIDE_DEFINE_REDUCTION(BF16, BF16)
TENSOR0_STRIDE_DEFINE_REDUCTION(F64, F64)
TENSOR0_STRIDE_DEFINE_REDUCTION(S64, S64)
TENSOR0_STRIDE_DEFINE_REDUCTION(S16, S16)
TENSOR0_STRIDE_DEFINE_REDUCTION(U8, U8)
TENSOR0_STRIDE_DEFINE_REDUCTION(U32, U32)

TENSOR0_STRIDE_DEFINE_ACCUMULATION(F32, F32)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(BF16, BF16)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(F64, F64)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(S64, S64)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(S16, S16)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(U8, U8)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(U32, U32)

#undef TENSOR0_STRIDE_DEFINE_REDUCTION
#undef TENSOR0_STRIDE_DEFINE_ACCUMULATION
