#include "reduction_impl.h"

TENSOR0_STRIDE_DEFINE_REDUCTION(S32, S32)
TENSOR0_STRIDE_DEFINE_REDUCTION(F16, F16)
TENSOR0_STRIDE_DEFINE_REDUCTION(C64, C64)
TENSOR0_STRIDE_DEFINE_REDUCTION(C128, C128)
TENSOR0_STRIDE_DEFINE_REDUCTION(U64, U64)
TENSOR0_STRIDE_DEFINE_REDUCTION(S8, S8)
TENSOR0_STRIDE_DEFINE_REDUCTION(U16, U16)
TENSOR0_STRIDE_DEFINE_REDUCTION(Pred, PRED)

TENSOR0_STRIDE_DEFINE_ACCUMULATION(S32, S32)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(F16, F16)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(C64, C64)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(C128, C128)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(U64, U64)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(S8, S8)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(U16, U16)
TENSOR0_STRIDE_DEFINE_ACCUMULATION(Pred, PRED)

#undef TENSOR0_STRIDE_DEFINE_REDUCTION
#undef TENSOR0_STRIDE_DEFINE_ACCUMULATION
