#include "update_impl.h"

TENSOR0_STRIDE_DEFINE_UPDATE(S32, S32)
TENSOR0_STRIDE_DEFINE_UPDATE(F16, F16)
TENSOR0_STRIDE_DEFINE_UPDATE(C64, C64)
TENSOR0_STRIDE_DEFINE_UPDATE(C128, C128)
TENSOR0_STRIDE_DEFINE_UPDATE(U64, U64)
TENSOR0_STRIDE_DEFINE_UPDATE(S8, S8)
TENSOR0_STRIDE_DEFINE_UPDATE(U16, U16)
TENSOR0_STRIDE_DEFINE_UPDATE(Pred, PRED)

#undef TENSOR0_STRIDE_DEFINE_UPDATE
